//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpKeep.ClientMaster {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://useupkeep.com/", ConfigurationName="ClientMaster.Master_ServiceSoap")]
    public interface Master_ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/getClientReference", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getClientReference(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/getClientReference", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getClientReferenceAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/getClientConnectionString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getClientConnectionString(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/getClientConnectionString", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getClientConnectionStringAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/getClientConnectionString_mobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getClientConnectionString_mobile(string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/getClientConnectionString_mobile", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getClientConnectionString_mobileAsync(string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Get_Client_Module_Rights", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get_Client_Module_Rights(int Client_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Get_Client_Module_Rights", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Get_Client_Module_RightsAsync(int Client_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Country_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Country_GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Country_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Country_GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Country_Search_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Country_Search_GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Country_Search_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Country_Search_GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Country_Master_Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Country_Master_Save(int Country_ID, string Country_Name, int Active, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Country_Master_Save", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Country_Master_SaveAsync(int Country_ID, string Country_Name, int Active, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/State_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable State_GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/State_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> State_GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/State_Search_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable State_Search_GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/State_Search_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> State_Search_GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/State_Master_Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int State_Master_Save(int State_ID, string State_Name, int Active, string Remark, int Country_Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/State_Master_Save", ReplyAction="*")]
        System.Threading.Tasks.Task<int> State_Master_SaveAsync(int State_ID, string State_Name, int Active, string Remark, int Country_Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/IDProof_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable IDProof_GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/IDProof_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> IDProof_GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/IDProof_Search_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable IDProof_Search_GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/IDProof_Search_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> IDProof_Search_GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/IDProof_Master_Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int IDProof_Master_Save(int IDProof_ID, string IDProof_Name, int Active, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/IDProof_Master_Save", ReplyAction="*")]
        System.Threading.Tasks.Task<int> IDProof_Master_SaveAsync(int IDProof_ID, string IDProof_Name, int Active, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Module_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Module_GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Module_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Module_GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Module_Search_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Module_Search_GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Module_Search_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Module_Search_GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Module_Master_Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Module_Master_Save(int Module_ID, string Module_Name, int Active, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Module_Master_Save", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Module_Master_SaveAsync(int Module_ID, string Module_Name, int Active, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Client_Master_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Client_Master_GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Client_Master_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Client_Master_GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Client_Master_Search_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Client_Master_Search_GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Client_Master_Search_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Client_Master_Search_GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Client_Master_Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Client_Master_Save(
                    int Client_ID, 
                    string Client_Name, 
                    string Client_Address, 
                    int City_ID, 
                    int State_ID, 
                    int Country_ID, 
                    int PIN_No, 
                    int Mobile_No, 
                    int Phone, 
                    string Email_ID, 
                    string Billing_Address, 
                    string Pan_No, 
                    int ID_Proff_ID, 
                    string ID_Proff_Detail, 
                    int Active, 
                    string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Client_Master_Save", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Client_Master_SaveAsync(
                    int Client_ID, 
                    string Client_Name, 
                    string Client_Address, 
                    int City_ID, 
                    int State_ID, 
                    int Country_ID, 
                    int PIN_No, 
                    int Mobile_No, 
                    int Phone, 
                    string Email_ID, 
                    string Billing_Address, 
                    string Pan_No, 
                    int ID_Proff_ID, 
                    string ID_Proff_Detail, 
                    int Active, 
                    string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/City_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable City_GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/City_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> City_GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/City_Search_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable City_Search_GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/City_Search_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> City_Search_GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/City_Master_Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int City_Master_Save(int City_ID, string City_Name, int Active, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/City_Master_Save", ReplyAction="*")]
        System.Threading.Tasks.Task<int> City_Master_SaveAsync(int City_ID, string City_Name, int Active, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/ClientConfig_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ClientConfig_GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/ClientConfig_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ClientConfig_GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/ClientConfig_Search_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ClientConfig_Search_GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/ClientConfig_Search_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ClientConfig_Search_GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/ClientConfig_Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ClientConfig_Save(int Config_ID, string Config_Name, string User_Name, string Password, bool Is_Link_To_Exists, string Web_service_IP, string URL, string Android_App_Name, string Android_App_URL, string Apple_App_Name, string Apple_App_URL, string Theme_Name, int Active, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/ClientConfig_Save", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ClientConfig_SaveAsync(int Config_ID, string Config_Name, string User_Name, string Password, bool Is_Link_To_Exists, string Web_service_IP, string URL, string Android_App_Name, string Android_App_URL, string Apple_App_Name, string Apple_App_URL, string Theme_Name, int Active, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/ModuleRights_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ModuleRights_GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/ModuleRights_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ModuleRights_GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/ModuleRights_Search_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ModuleRights_Search_GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/ModuleRights_Search_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ModuleRights_Search_GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/ModuleRights_Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ModuleRights_Save(int Rights_ID, int Module_ID, int Client_ID, string Module_Start_Date, string Module_End_Date, string Demo_Start_Date, string Demo_End_Date, int Alert_Days, int Active, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/ModuleRights_Save", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ModuleRights_SaveAsync(int Rights_ID, int Module_ID, int Client_ID, string Module_Start_Date, string Module_End_Date, string Demo_Start_Date, string Demo_End_Date, int Alert_Days, int Active, string Remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Send_Email", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Send_Email(string To, string Subject, string Body, string cdt, string privateKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://useupkeep.com/Send_Email", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Send_EmailAsync(string To, string Subject, string Body, string cdt, string privateKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Master_ServiceSoapChannel : UpKeep.ClientMaster.Master_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Master_ServiceSoapClient : System.ServiceModel.ClientBase<UpKeep.ClientMaster.Master_ServiceSoap>, UpKeep.ClientMaster.Master_ServiceSoap {
        
        public Master_ServiceSoapClient() {
        }
        
        public Master_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Master_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Master_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Master_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string getClientReference(string url) {
            return base.Channel.getClientReference(url);
        }
        
        public System.Threading.Tasks.Task<string> getClientReferenceAsync(string url) {
            return base.Channel.getClientReferenceAsync(url);
        }
        
        public System.Data.DataTable getClientConnectionString(string url) {
            return base.Channel.getClientConnectionString(url);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getClientConnectionStringAsync(string url) {
            return base.Channel.getClientConnectionStringAsync(url);
        }
        
        public string getClientConnectionString_mobile(string mobile) {
            return base.Channel.getClientConnectionString_mobile(mobile);
        }
        
        public System.Threading.Tasks.Task<string> getClientConnectionString_mobileAsync(string mobile) {
            return base.Channel.getClientConnectionString_mobileAsync(mobile);
        }
        
        public System.Data.DataTable Get_Client_Module_Rights(int Client_ID) {
            return base.Channel.Get_Client_Module_Rights(Client_ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Get_Client_Module_RightsAsync(int Client_ID) {
            return base.Channel.Get_Client_Module_RightsAsync(Client_ID);
        }
        
        public System.Data.DataTable Country_GetData() {
            return base.Channel.Country_GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Country_GetDataAsync() {
            return base.Channel.Country_GetDataAsync();
        }
        
        public System.Data.DataTable Country_Search_GetData() {
            return base.Channel.Country_Search_GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Country_Search_GetDataAsync() {
            return base.Channel.Country_Search_GetDataAsync();
        }
        
        public int Country_Master_Save(int Country_ID, string Country_Name, int Active, string Remark) {
            return base.Channel.Country_Master_Save(Country_ID, Country_Name, Active, Remark);
        }
        
        public System.Threading.Tasks.Task<int> Country_Master_SaveAsync(int Country_ID, string Country_Name, int Active, string Remark) {
            return base.Channel.Country_Master_SaveAsync(Country_ID, Country_Name, Active, Remark);
        }
        
        public System.Data.DataTable State_GetData() {
            return base.Channel.State_GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> State_GetDataAsync() {
            return base.Channel.State_GetDataAsync();
        }
        
        public System.Data.DataTable State_Search_GetData() {
            return base.Channel.State_Search_GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> State_Search_GetDataAsync() {
            return base.Channel.State_Search_GetDataAsync();
        }
        
        public int State_Master_Save(int State_ID, string State_Name, int Active, string Remark, int Country_Code) {
            return base.Channel.State_Master_Save(State_ID, State_Name, Active, Remark, Country_Code);
        }
        
        public System.Threading.Tasks.Task<int> State_Master_SaveAsync(int State_ID, string State_Name, int Active, string Remark, int Country_Code) {
            return base.Channel.State_Master_SaveAsync(State_ID, State_Name, Active, Remark, Country_Code);
        }
        
        public System.Data.DataTable IDProof_GetData() {
            return base.Channel.IDProof_GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> IDProof_GetDataAsync() {
            return base.Channel.IDProof_GetDataAsync();
        }
        
        public System.Data.DataTable IDProof_Search_GetData() {
            return base.Channel.IDProof_Search_GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> IDProof_Search_GetDataAsync() {
            return base.Channel.IDProof_Search_GetDataAsync();
        }
        
        public int IDProof_Master_Save(int IDProof_ID, string IDProof_Name, int Active, string Remark) {
            return base.Channel.IDProof_Master_Save(IDProof_ID, IDProof_Name, Active, Remark);
        }
        
        public System.Threading.Tasks.Task<int> IDProof_Master_SaveAsync(int IDProof_ID, string IDProof_Name, int Active, string Remark) {
            return base.Channel.IDProof_Master_SaveAsync(IDProof_ID, IDProof_Name, Active, Remark);
        }
        
        public System.Data.DataTable Module_GetData() {
            return base.Channel.Module_GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Module_GetDataAsync() {
            return base.Channel.Module_GetDataAsync();
        }
        
        public System.Data.DataTable Module_Search_GetData() {
            return base.Channel.Module_Search_GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Module_Search_GetDataAsync() {
            return base.Channel.Module_Search_GetDataAsync();
        }
        
        public int Module_Master_Save(int Module_ID, string Module_Name, int Active, string Remark) {
            return base.Channel.Module_Master_Save(Module_ID, Module_Name, Active, Remark);
        }
        
        public System.Threading.Tasks.Task<int> Module_Master_SaveAsync(int Module_ID, string Module_Name, int Active, string Remark) {
            return base.Channel.Module_Master_SaveAsync(Module_ID, Module_Name, Active, Remark);
        }
        
        public System.Data.DataTable Client_Master_GetData() {
            return base.Channel.Client_Master_GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Client_Master_GetDataAsync() {
            return base.Channel.Client_Master_GetDataAsync();
        }
        
        public System.Data.DataTable Client_Master_Search_GetData() {
            return base.Channel.Client_Master_Search_GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Client_Master_Search_GetDataAsync() {
            return base.Channel.Client_Master_Search_GetDataAsync();
        }
        
        public int Client_Master_Save(
                    int Client_ID, 
                    string Client_Name, 
                    string Client_Address, 
                    int City_ID, 
                    int State_ID, 
                    int Country_ID, 
                    int PIN_No, 
                    int Mobile_No, 
                    int Phone, 
                    string Email_ID, 
                    string Billing_Address, 
                    string Pan_No, 
                    int ID_Proff_ID, 
                    string ID_Proff_Detail, 
                    int Active, 
                    string Remark) {
            return base.Channel.Client_Master_Save(Client_ID, Client_Name, Client_Address, City_ID, State_ID, Country_ID, PIN_No, Mobile_No, Phone, Email_ID, Billing_Address, Pan_No, ID_Proff_ID, ID_Proff_Detail, Active, Remark);
        }
        
        public System.Threading.Tasks.Task<int> Client_Master_SaveAsync(
                    int Client_ID, 
                    string Client_Name, 
                    string Client_Address, 
                    int City_ID, 
                    int State_ID, 
                    int Country_ID, 
                    int PIN_No, 
                    int Mobile_No, 
                    int Phone, 
                    string Email_ID, 
                    string Billing_Address, 
                    string Pan_No, 
                    int ID_Proff_ID, 
                    string ID_Proff_Detail, 
                    int Active, 
                    string Remark) {
            return base.Channel.Client_Master_SaveAsync(Client_ID, Client_Name, Client_Address, City_ID, State_ID, Country_ID, PIN_No, Mobile_No, Phone, Email_ID, Billing_Address, Pan_No, ID_Proff_ID, ID_Proff_Detail, Active, Remark);
        }
        
        public System.Data.DataTable City_GetData() {
            return base.Channel.City_GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> City_GetDataAsync() {
            return base.Channel.City_GetDataAsync();
        }
        
        public System.Data.DataTable City_Search_GetData() {
            return base.Channel.City_Search_GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> City_Search_GetDataAsync() {
            return base.Channel.City_Search_GetDataAsync();
        }
        
        public int City_Master_Save(int City_ID, string City_Name, int Active, string Remark) {
            return base.Channel.City_Master_Save(City_ID, City_Name, Active, Remark);
        }
        
        public System.Threading.Tasks.Task<int> City_Master_SaveAsync(int City_ID, string City_Name, int Active, string Remark) {
            return base.Channel.City_Master_SaveAsync(City_ID, City_Name, Active, Remark);
        }
        
        public System.Data.DataTable ClientConfig_GetData() {
            return base.Channel.ClientConfig_GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ClientConfig_GetDataAsync() {
            return base.Channel.ClientConfig_GetDataAsync();
        }
        
        public System.Data.DataTable ClientConfig_Search_GetData() {
            return base.Channel.ClientConfig_Search_GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ClientConfig_Search_GetDataAsync() {
            return base.Channel.ClientConfig_Search_GetDataAsync();
        }
        
        public int ClientConfig_Save(int Config_ID, string Config_Name, string User_Name, string Password, bool Is_Link_To_Exists, string Web_service_IP, string URL, string Android_App_Name, string Android_App_URL, string Apple_App_Name, string Apple_App_URL, string Theme_Name, int Active, string Remark) {
            return base.Channel.ClientConfig_Save(Config_ID, Config_Name, User_Name, Password, Is_Link_To_Exists, Web_service_IP, URL, Android_App_Name, Android_App_URL, Apple_App_Name, Apple_App_URL, Theme_Name, Active, Remark);
        }
        
        public System.Threading.Tasks.Task<int> ClientConfig_SaveAsync(int Config_ID, string Config_Name, string User_Name, string Password, bool Is_Link_To_Exists, string Web_service_IP, string URL, string Android_App_Name, string Android_App_URL, string Apple_App_Name, string Apple_App_URL, string Theme_Name, int Active, string Remark) {
            return base.Channel.ClientConfig_SaveAsync(Config_ID, Config_Name, User_Name, Password, Is_Link_To_Exists, Web_service_IP, URL, Android_App_Name, Android_App_URL, Apple_App_Name, Apple_App_URL, Theme_Name, Active, Remark);
        }
        
        public System.Data.DataTable ModuleRights_GetData() {
            return base.Channel.ModuleRights_GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ModuleRights_GetDataAsync() {
            return base.Channel.ModuleRights_GetDataAsync();
        }
        
        public System.Data.DataTable ModuleRights_Search_GetData() {
            return base.Channel.ModuleRights_Search_GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ModuleRights_Search_GetDataAsync() {
            return base.Channel.ModuleRights_Search_GetDataAsync();
        }
        
        public int ModuleRights_Save(int Rights_ID, int Module_ID, int Client_ID, string Module_Start_Date, string Module_End_Date, string Demo_Start_Date, string Demo_End_Date, int Alert_Days, int Active, string Remark) {
            return base.Channel.ModuleRights_Save(Rights_ID, Module_ID, Client_ID, Module_Start_Date, Module_End_Date, Demo_Start_Date, Demo_End_Date, Alert_Days, Active, Remark);
        }
        
        public System.Threading.Tasks.Task<int> ModuleRights_SaveAsync(int Rights_ID, int Module_ID, int Client_ID, string Module_Start_Date, string Module_End_Date, string Demo_Start_Date, string Demo_End_Date, int Alert_Days, int Active, string Remark) {
            return base.Channel.ModuleRights_SaveAsync(Rights_ID, Module_ID, Client_ID, Module_Start_Date, Module_End_Date, Demo_Start_Date, Demo_End_Date, Alert_Days, Active, Remark);
        }
        
        public string Send_Email(string To, string Subject, string Body, string cdt, string privateKey) {
            return base.Channel.Send_Email(To, Subject, Body, cdt, privateKey);
        }
        
        public System.Threading.Tasks.Task<string> Send_EmailAsync(string To, string Subject, string Body, string cdt, string privateKey) {
            return base.Channel.Send_EmailAsync(To, Subject, Body, cdt, privateKey);
        }
    }
}
