using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DLL
{
    public class SProc
    {
        //For Master
        public string Get_Client_Module_Rights = "Get_Client_Module_Rights";
        public string CLIENT_CONFIG_MASTERSELECT = "usp_Client_Config_MasterSelect";
        public string Country_Master_GetData = "Country_Master_GetData";
        public string Country_Master_Search_GetData = "Country_Master_Search_GetData";
        public string Country_Master_Save = "Country_Master_Save";
        public string City_Master_GetData = "City_Master_GetData";
        public string City_Master_Search_GetData = "City_Master_Search_GetData";
        public string City_Master_Save = "City_Master_Save";
        public string ClientConfig_Master_GetData = "ClientConfig_Master_GetData";
        public string ClientConfig_Master_Search_GetData = "ClientConfig_Master_Search_GetData";
        public string ClientConfig_Master_Save = "ClientConfig_Master_Save";
        public string ModuleRights_Master_GetData = "ModuleRights_Master_GetData";
        public string ModuleRights_Master_Search_GetData = "ModuleRights_Master_Search_GetData";
        public string ModuleRights_Master_Save = "ModuleRights_Master_Save";
        //For Client
        public string User_Login_Master_GetData = "User_Login_Master_GetData";
        public string User_Login_Search_GetData = "User_Login_Search_GetData";
        public string User_Login_Save = "User_Login_Save";
        public string Assesment_Master_GetData = "Assesment_Master_GetData";
        public string Assessment_Master_Search_GetData = "Assessment_Master_Search_GetData";
        public string Assesment_Master_Save = "Assesment_Master_Save";
        public string Category_Master_GetData = "Category_Master_GetData";
        public string Category_Master_Search_GetData = "Category_Master_Search_GetData";
        public string Category_Master_Save = "Category_Master_Save";
        public string Frequency_Master_GetData = "Frequency_Master_GetData";
        public string Frequency_Master_Search_GetData = "Frequency_Master_Search_GetData";
        public string Frequency_Master_Save = "Frequency_Master_Save";
        public string Holiday_Master_GetData = "Holiday_Master_GetData";
        public string Holiday_Master_Search_GetData = "Holiday_Master_Search_GetData";
        public string Holiday_Master_Save = "Holiday_Master_Save";
        public string Location_Master_GetData = "Location_Master_GetData";
        public string Location_Master_Search_GetData = "Location_Master_Search_GetData";
        public string Location_Master_Save = "Location_Master_Save";
        public string Metting_Room_Master_GetData = "Metting_Room_Master_GetData";
        public string Metting_Room_Master_Search_GetData = "Metting_Room_Master_Search_GetData";
        public string Metting_Room_Master_Save = "Metting_Room_Master_Save";
        public string Module_Master_GetData = "Module_Master_GetData";
        public string Module_Master_Search_GetData = "Module_Master_Search_GetData";
        public string Module_Master_Save = "Module_Master_Save";
        public string Priority_Master_GetData = "Priority_Master_GetData";
        public string Priority_Master_Search_GetData = "Priority_Master_Search_GetData";
        public string Priority_Master_Save = "Priority_Master_Save";
        public string Request_Status_Master_GetData = "Request_Status_Master_GetData";
        public string Request_Status_Master_Search_GetData = "Request_Status_Master_Search_GetData";
        public string Request_Status_Master_Save = "Request_Status_Master_Save";
        public string Schedule_Master_GetData = "Schedule_Master_GetData";
        public string Schedule_Master_Search_GetData = "Schedule_Master_Search_GetData";
        public string Schedule_Master_Save = "Schedule_Master_Save";
        public string Sub_Assessment_Master_GetData = "Sub_Assessment_Master_GetData";
        public string Sub_Assessment_Master_Search_GetData = "Sub_Assessment_Master_Search_GetData";
        public string Sub_Assessment_Master_Save = "Sub_Assessment_Master_Save";
        public string Task_Master_GetData = "Task_Master_GetData";
        public string Task_Master_GetData_ByIds = "Task_Master_GetData_ByIds";
        public string Task_Master_Search_GetData = "Task_Master_Search_GetData";
        public string Task_Master_Save = "Task_Master_Save";
        public string Task_Transaction_Master_GetData = "Task_Transaction_Master_GetData";
        public string Task_Transaction_Master_Search_GetData = "Task_Transaction_Master_Search_GetData";
        public string Task_Transaction_Master_Save = "Task_Transaction_Master_Save";
        public string User_Catogry_Master_GetData = "User_Catogry_Master_GetData";
        public string User_Rights_Master_Save = "User_Rights_Master_Save";
        public string WeekllyOff_Master_GetData = "WeekllyOff_Master_GetData";
        public string WeekllyOff_Master_Search_GetData = "WeekllyOff_Master_Search_GetData";
        public string WeekllyOff_Master_Save = "WeekllyOff_Master_Save";
        public string Work_Request_Master_GetData = "Work_Request_Master_GetData";
        public string Work_Request_Master_Search_GetData = "Work_Request_Master_Search_GetData";
        public string Work_Request_Master_Save = "Work_Request_Master_Save";
        public string Work_Status_GetData = "Work_Status_GetData";
        public string Work_Status_Search_GetData = "Work_Status_Search_GetData";
        public string Work_Status_Master_Save = "Work_Status_Master_Save";
        public string Visitor_Master_GetData = "Visitor_Master_GetData";
        public string Visitor_Master_Search_GetData = "Visitor_Master_Search_GetData";
        public string Visitor_Master_Save = "Visitor_Master_Save";
        public string Client_Config_Mobile_Select = "usp_Client_Config_Mobile_Select";
        public string Unit_Master_GetData = "Unit_Master_GetData";
        public string Unit_Master_Save = "Unit_Master_Save";
        public string Item_Group_Master_GetData = "Item_Group_Master_GetData";
        public string Item_Group_Master_Save = "Item_Group_Master_Save";
        public string Item_Hsn_Master_GetData = "Item_Hsn_Master_GetData";
        public string Item_Hsn_Master_Save = "Item_Hsn_Master_Save";
        public string Item_Category_Master_GetData = "Item_Category_Master_GetData";
        public string Item_Category_Master_Save = "Item_Category_Master_Save";
        public string Item_Master_GetData = "Item_Master_GetData";
        public string Item_Master_Save = "Item_Master_Save";
        public string Item_Detail_GetData = "Item_Detail_GetData";
        public string Item_Detail_Save = "Item_Detail_Save";
        public string Company_Master_GetData = "Company_Master_GetData";
        public string Company_Master_Save = "Company_Master_Save";
        public string Branch_Master_GetData = "Branch_Master_GetData";
        public string Branch_Master_Save = "Branch_Master_Save";
        public string Ledger_Master_GetData = "Ledger_Master_GetData";
        public string Ledger_Master_Save = "Ledger_Master_Save";
        public string Ledger_Opening_GetData = "Ledger_Opening_GetData";
        public string Ledger_Opening_Save = "Ledger_Opening_Save";
        public string Financial_Year_Master_GetData = "Financial_Year_Master_GetData";
        public string Financial_Year_Master_Save = "Financial_Year_Master_Save";
        public string Item_Invoice_Detail_Delete = "Item_Invoice_Detail_Delete";
        public string Item_Master_Delete = "Item_Master_Delete";
        public string Task_Transaction_User_GetData = "Task_Transaction_User_GetData";
        public string Task_User_Update = "Task_User_Update";
        public string Task_User_UpdateStartStop = "Task_User_UpdateStartStop";
        public string Task_Transaction_AllUser_GetData = "Task_Transaction_AllUser_GetData";
        public string GetUserTaskAssignedHours = "GetUserTaskAssignedHours";
        public string Task_UserTested_Update = "Task_UserTested_Update";
        public string GetUserWorkingHours = "GetUserWorkingHours";
        public string SP_getProjectTaskCount = "SP_getProjectTaskCount";
        public string UpdateUserName = "UpdateUserName";
        public string Get_User_Rights_With_Module = "select_rights";
        public string User_Rights_Delete = "User_Rights_Delete";
        public string Assign_Task_Delete = "Assign_Task_Delete";

        public string IDProof_Master_Save = "IDProof_Master_Save";
        public string Assessment_DropDown_GetData = "Assessment_DropDown_GetData";
    }
}
